// <auto-generated />
namespace PopsDogCatching_API.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class OverHaulB : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(OverHaulB));
        
        string IMigrationMetadata.Id
        {
            get { return "202108050130248_OverHaulB"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
