// <auto-generated />
namespace PopsDogCatching_API.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddedRouteID_to_Employee_and_EmployeeID_to_Route : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedRouteID_to_Employee_and_EmployeeID_to_Route));
        
        string IMigrationMetadata.Id
        {
            get { return "202108041022047_AddedRouteID_to_Employee_and_EmployeeID_to_Route"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
